# @package _global_

DEBUG: false
PROFILE: false

trainer:  
  epochs: 100
  optimizer: torch.optim.Adam
  lr: 0.0008
dataset:
  path: /home/jarybski/Desktop/Animal-10/archive/raw-img
  img_size: 256
  batch_size: 10
  shuffle: True
  pin_memory: False
  sampler: False
  random_state: 192
  batch_sampler: False
  num_workers: 2
  collate_fn: false
  pin_memory: False
  drop_last: False
  timeout: 0
  prefetch_factor: 2
  persistent_workers: False
  
